### ISSUE TITLE
Divvun (sme) issues error message about overlapping I/O

### ISSUE THREAD

**Issue by albbas** [TinoDidriksen/spellers#20] opened 2016-01-29 10:34 UTC
After upgrading to a version that fixes issue 18, an error message about overlapping I/O is issued when continuous spell checking is on. 

![windows-error-message](https://cloud.githubusercontent.com/assets/75695/12673253/ccf506ea-c67b-11e5-997c-01938571b8e1.png)

OS: windows 7 enterprise service pack 1, 64 bit
Word: Microsoft Office Professional Plus 2013, 32 bit

**Comment by TinoDidriksen** [comment] 2016-01-29 12:34
That was sort of on purpose. That means the backend died, and shows me where it died. I can make it silent. How often does it happen?

I still can't reproduce this, though. Maybe I need to create a logger build to get more feedback...

**Comment by TinoDidriksen** [comment] 2016-01-29 13:16
Btw, how fast is the machine this happens on? How overloaded is it? I noted the popup looks ancient.

There is a 7 second timeout on the read, and I'd guess this happens because it takes more than 7 seconds to even launch the backend on that machine.

**Comment by TinoDidriksen** [comment] 2016-02-09 22:20
Fixed in Apertium svn revision 65504, and all speller packages regenerated.

**Closed as completed by TinoDidriksen** 2016-02-09 22:20 UTC
